name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Run Checkstyle linter
      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw
      
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check

      - name: Build with Maven
        run: |
          ./mvnw clean package

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: '.'
          severity: "HIGH,CRITICAL"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Bakops_EPIVIZ-API-SPRING
            -Dsonar.organization=bakops
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: epivizappapi-jar
          path: target/*.jar

      - name: Build Docker image
        run: |
          docker build -t bakops224/epivizappapi:latest .

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        run: |
          docker push bakops224/epivizappapi:latest
